# Generated by Django 3.1.1 on 2021-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20210115_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
