# Generated by Django 3.1.1 on 2021-01-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('analytics', '0007_auto_20210115_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
