# Generated by Django 3.1.1 on 2021-01-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_pagevisit_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='session',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
